# Gauss-Jordan Elimination
- a systematic way to find solution to a linear system


## Success Case: when a matrix is non-singular (invertible, full rank, n pivots)
1. suppose we have a linear system as the following:
- (eq.1) $x + 2y + z = 2$ 
- (eq.2) $3x + 8y + z = 12$ 
- (eq.3) $4y + z = 2$ 

- We can make the above linear system into the simple form where
$ A =  \begin{bmatrix}
1 & 2 & 1 \\
3 & 8 & 1 \\
0 & 4 & 1 \\
\end{bmatrix}
$ and $b = \begin{bmatrix} 2 \\ 12 \\ 2 \end{bmatrix}$

In [89]:
import numpy as np

A = np.array([[1,2,1], [3, 8, 1], [0, 4, 1]])
# reshaping b into 3 by 1 matrix
b = np.array([2, 12, 2]).reshape(3, 1)

print(A)
print(b)

[[1 2 1]
 [3 8 1]
 [0 4 1]]
[[ 2]
 [12]
 [ 2]]


2. Gaussian elimination goal is to make matrix A to U where U is the upper-triangular matrix
- suppose we only consider matrix A
- we can eliminate x from equation 2 by subtracting 3 times (eq.1) from (eq.2)

In [90]:
# get second row of A
A[1, :]

# subtract 3 (row 1) from (row 2)
A[1, :] = A[1, :] - 3 * A[0, :]

In [91]:
print(A)

[[ 1  2  1]
 [ 0  2 -2]
 [ 0  4  1]]


- now, below $a_{11}$, all are zero, therefore, $a_{11}$ is pivot
- next, beside first column and first row, 2 in $a_{22}$ is pivot position
- we take away 2 times (row 2) from (row 3)

In [92]:
# subtract 2 times (row 2) from (row 3)
A[2, :] = A[2, :] - 2 * A[1, :]

In [93]:
# show echelon form
print(A)

[[ 1  2  1]
 [ 0  2 -2]
 [ 0  0  5]]


- we can check that all columns and rows have pivots.
- later, we will call this full rank matrix
- also, this matrix is invertible (we will check later)

3. Augmented matrix
- let's make $A$ into an augmented matrix $[A | b]$

In [94]:
# now, initialize A as the original A
A = np.array([[1,2,1], [3, 8, 1], [0, 4, 1]])

# define Ab as the augmented matrix
Ab = np.hstack((A, b))
print(Ab)

[[ 1  2  1  2]
 [ 3  8  1 12]
 [ 0  4  1  2]]


- we can make our matrix Ab into echelon form with the same steps


In [95]:
# subtract 3 (row 1) from (row 2) 
Ab[1, :] = Ab[1, :] - 3 * Ab[0, :]

# subtract 2 times (row 2) from (row 3)
Ab[2, :] = Ab[2, :] - 2 * Ab[1, :]

In [96]:
print(Ab)

[[  1   2   1   2]
 [  0   2  -2   6]
 [  0   0   5 -10]]


- matrix Ab is now 'echelon form'

4. Gauss-Jordan elimination
- first scale all pivots into 1

In [97]:
# 2nd pivot has to be 1
Ab[1, :] = 1/2 * Ab[1, :]

# 3rd pivot has to be 1
Ab[2, :] = 1/5 * Ab[2, :]

In [98]:
Ab

array([[ 1,  2,  1,  2],
       [ 0,  1, -1,  3],
       [ 0,  0,  1, -2]])

- <b>reduce row echelon form (RREF)</b>: all pivot columns have only nonzero element at the pivot position

In [99]:
# add (row 3) to (row 2)
Ab[1, :] = Ab[1, :] + Ab[2, :]

# subtract (row 3) from (row 1)
Ab[0, :] = Ab[0, :] - Ab[2, :]

In [104]:
Ab

array([[ 1,  2,  0,  4],
       [ 0,  1,  0,  1],
       [ 0,  0,  1, -2]])

In [105]:
# subtract 2 * (row 2) from (row 1)
Ab[0, :] = Ab[0, :] - 2 * Ab[1, :]

In [106]:
Ab

array([[ 1,  0,  0,  2],
       [ 0,  1,  0,  1],
       [ 0,  0,  1, -2]])

Now, the solution to the system: 
- (eq.1) $x + 2y + z = 2$ 
- (eq.2) $3x + 8y + z = 12$ 
- (eq.3) $4y + z = 2$
- 
$x = 2, y = 1, z = -2$

In python, we can get row-reduce echelon matrix using a function in 'sympy' library: 

In [108]:
import sympy 

# now, initialize A as the original A
A = np.array([[1,2,1], [3, 8, 1], [0, 4, 1]])

# define Ab as the augmented matrix
Ab = np.hstack((A, b))

print(sympy.Matrix(Ab).rref())

(Matrix([
[1, 0, 0,  2],
[0, 1, 0,  1],
[0, 0, 1, -2]]), (0, 1, 2))


## Failure case: when a matrix is singular (non-invertible, determinant = 0)
- Suppose a linear system is 
- (eq.1) $x + 2y + 3z = 3$ 
- (eq.2) $2x + 4y + 5z = 5$ 
- (eq.3) $3x + 6y + 8z = 8$


In [120]:
# create matrix A using reshape
A = np.array([1, 2, 3, 2, 4, 5, 3, 6, 8]).reshape(3,3)

In [123]:
# shape of A
A.shape

(3, 3)

In [124]:
# create vector b
b = np.array([3, 5, 8]).reshape(3, 1)

In [126]:
# augmented matrix
Ab = np.hstack((A, b))

In [127]:
Ab

array([[1, 2, 3, 3],
       [2, 4, 5, 5],
       [3, 6, 8, 8]])

* Gauss Jordan Elimination

In [128]:
# r2 = r2 - 2*r1
Ab[1, :] = Ab[1, :] - 2 * Ab[0, :]

In [129]:
# r3 = r3 - 3*r1
Ab[2, :] = Ab[2, :] - 3 * Ab[0, :]

In [130]:
Ab

array([[ 1,  2,  3,  3],
       [ 0,  0, -1, -1],
       [ 0,  0, -1, -1]])

- we don't have pivot in 2nd column

In [131]:
# r3 = r3 - r2
Ab[2, :] = Ab[2, :] - Ab[1, :]

In [132]:
Ab

array([[ 1,  2,  3,  3],
       [ 0,  0, -1, -1],
       [ 0,  0,  0,  0]])

- we see that pivots are in column 1 and column 3, not column 2
- thus, the matrix is not full rank
- not invertible and singular

Further Gauss-Jordan yields:

In [133]:
# r2 = -1 * r2
Ab[1, :] = -1 * Ab[1, :]

In [134]:
# r1 = r1 - 3 * r2
Ab[0, :] = Ab[0, :] - 3 * Ab[1, :]

In [135]:
Ab

array([[1, 2, 0, 0],
       [0, 0, 1, 1],
       [0, 0, 0, 0]])